from datetime import datetime, timedelta

from fastapi import APIRouter, Depends
from sqlmodel import Session

from app.database import get_session
from app.schemas import EventCreate, ScheduleRequest, ScheduleResponse

router = APIRouter(prefix="/api/schedule", tags=["schedule"])


@router.post("/generate", response_model=ScheduleResponse)
def generate_schedule(payload: ScheduleRequest, session: Session = Depends(get_session)):
    """Turn a list of tasks into calendar events.

    Skeleton implementation: lays each task out in sequential one-hour blocks
    starting from the next whole hour. The AI-driven planning (via Ollama) will
    replace this naive logic later.
    """
    start = datetime.utcnow().replace(minute=0, second=0, microsecond=0) + timedelta(hours=1)

    events: list[EventCreate] = []
    for index, task in enumerate(payload.tasks):
        slot_start = start + timedelta(hours=index)
        events.append(
            EventCreate(
                title=task,
                start_time=slot_start,
                end_time=slot_start + timedelta(hours=1),
                description="Auto-generated by Dispatch",
                agent_id=payload.agent_id,
            )
        )

    return ScheduleResponse(events=events)
